  SET SERVEROUTPUT ON;

  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SERVICE_RECORD CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PAYMENT CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RESERVATION_ROOM CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RESERVATION CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROOM CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SERVICE CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROOM_TYPE CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STAFF CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROLE CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GUEST CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE HOTEL CASCADE CONSTRAINTS';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /

  -- Drop sequences
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE GUEST_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE HOTEL_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ROLE_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE STAFF_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ROOM_TYPE_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ROOM_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SERVICE_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE RESERVATION_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE PAYMENT_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /
  BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SERVICE_RECORD_SEQ';
  EXCEPTION WHEN OTHERS THEN NULL; END;
  /


  CREATE SEQUENCE GUEST_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE HOTEL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE ROLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE STAFF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE ROOM_TYPE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE ROOM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE SERVICE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE RESERVATION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
  CREATE SEQUENCE SERVICE_RECORD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- =====================================================
-- HOTEL
-- =====================================================
CREATE TABLE HOTEL (
    HOTEL_ID NUMBER CONSTRAINT HOTEL_HOTEL_ID_PK PRIMARY KEY,
    NAME VARCHAR2(100) CONSTRAINT HOTEL_NAME_NN NOT NULL,
    LOCATION VARCHAR2(150) CONSTRAINT HOTEL_LOCATION_NN NOT NULL
);

-- =====================================================
-- ROLE
-- =====================================================
CREATE TABLE ROLE (
    ROLE_ID NUMBER CONSTRAINT ROLE_ROLE_ID_PK PRIMARY KEY,
    NAME VARCHAR2(50) CONSTRAINT ROLE_NAME_NN NOT NULL
);

-- =====================================================
-- GUEST
-- =====================================================
CREATE TABLE GUEST (
    GUEST_ID NUMBER CONSTRAINT GUEST_GUEST_ID_PK PRIMARY KEY,
    NAME VARCHAR2(100) CONSTRAINT GUEST_NAME_NN NOT NULL,
    CONTACT_NO VARCHAR2(20) CONSTRAINT GUEST_CONTACT_NO_NN NOT NULL,
    EMAIL VARCHAR2(100) CONSTRAINT GUEST_EMAIL_UQ UNIQUE,
    ADDRESS VARCHAR2(200)
);

-- =====================================================
-- ROOM_TYPE
-- =====================================================
CREATE TABLE ROOM_TYPE (
    ROOM_TYPE_ID NUMBER CONSTRAINT ROOM_TYPE_ID_PK PRIMARY KEY,
    NAME VARCHAR2(50) CONSTRAINT ROOM_TYPE_NAME_NN NOT NULL,
    RATE NUMBER(10,2) CONSTRAINT ROOM_TYPE_RATE_NN NOT NULL,
    DESCRIPTION VARCHAR2(200),
    CONSTRAINT ROOM_TYPE_NAME_TYPE_CHK CHECK (NAME IN ('SINGLE','DOUBLE','SUITE')),
    CONSTRAINT ROOM_TYPE_RATE_VALUE_CHK CHECK (RATE > 0)
);

-- =====================================================
-- STAFF
-- =====================================================
CREATE TABLE STAFF (
    STAFF_ID NUMBER CONSTRAINT STAFF_STAFF_ID_PK PRIMARY KEY,
    HOTEL_ID NUMBER CONSTRAINT STAFF_HOTEL_ID_NN NOT NULL
        CONSTRAINT STAFF_HOTEL_ID_FK REFERENCES HOTEL(HOTEL_ID) ON DELETE CASCADE,
    ROLE_ID NUMBER CONSTRAINT STAFF_ROLE_ID_NN NOT NULL
        CONSTRAINT STAFF_ROLE_ID_FK REFERENCES ROLE(ROLE_ID) ON DELETE RESTRICT,
    NAME VARCHAR2(100) CONSTRAINT STAFF_NAME_NN NOT NULL,
    CONTACT_NO VARCHAR2(20),
    EMAIL VARCHAR2(100)
);

-- =====================================================
-- ROOM
-- =====================================================
CREATE TABLE ROOM (
    ROOM_ID NUMBER CONSTRAINT ROOM_ROOM_ID_PK PRIMARY KEY,
    HOTEL_ID NUMBER CONSTRAINT ROOM_HOTEL_ID_NN NOT NULL
        CONSTRAINT ROOM_HOTEL_ID_FK REFERENCES HOTEL(HOTEL_ID) ON DELETE CASCADE,
    ROOM_TYPE_ID NUMBER CONSTRAINT ROOM_ROOM_TYPE_ID_NN NOT NULL
        CONSTRAINT ROOM_ROOM_TYPE_ID_FK REFERENCES ROOM_TYPE(ROOM_TYPE_ID) ON DELETE RESTRICT,
    STATUS VARCHAR2(20) CONSTRAINT ROOM_STATUS_NN NOT NULL
        CONSTRAINT ROOM_STATUS_CHK CHECK (STATUS IN ('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE','CLEANING'))
);

-- =====================================================
-- SERVICE
-- =====================================================
CREATE TABLE SERVICE (
    SERVICE_ID NUMBER CONSTRAINT SERVICE_SERVICE_ID_PK PRIMARY KEY,
    NAME VARCHAR2(100) CONSTRAINT SERVICE_NAME_NN NOT NULL,
    SERVICE_CHARGE NUMBER(10,2) CONSTRAINT SERVICE_CHARGE_NN NOT NULL
        CONSTRAINT SERVICE_CHARGE_CHK CHECK (SERVICE_CHARGE >= 0)
);

-- =====================================================
-- RESERVATION
-- =====================================================
CREATE TABLE RESERVATION (
    RESERVATION_ID NUMBER CONSTRAINT RESERVATION_RESERVATION_ID_PK PRIMARY KEY,
    GUEST_ID NUMBER CONSTRAINT RESERVATION_GUEST_ID_NN NOT NULL
        CONSTRAINT RESERVATION_GUEST_ID_FK REFERENCES GUEST(GUEST_ID) ON DELETE RESTRICT,
    RESERVATION_DATE DATE CONSTRAINT RESERVATION_DATE_NN NOT NULL,
    CHECKIN_DATE DATE CONSTRAINT RESERVATION_CHECKIN_DATE_NN NOT NULL,
    CHECKOUT_DATE DATE CONSTRAINT RESERVATION_CHECKOUT_DATE_NN NOT NULL,
    STATUS VARCHAR2(20) CONSTRAINT RESERVATION_STATUS_NN NOT NULL
        CONSTRAINT RESERVATION_STATUS_CHK CHECK (STATUS IN ('BOOKED','CANCELLED','CHECKED_IN','CHECKED_OUT')),
    CONSTRAINT RESERVATION_DATES_CHK CHECK (CHECKOUT_DATE > CHECKIN_DATE)
);

-- =====================================================
-- RESERVATION_ROOM
-- =====================================================
CREATE TABLE RESERVATION_ROOM (
    RESERVATION_ID NUMBER CONSTRAINT RR_RES_ID_NN NOT NULL
        CONSTRAINT RR_RES_ID_FK REFERENCES RESERVATION(RESERVATION_ID) ON DELETE CASCADE,
    ROOM_ID NUMBER CONSTRAINT RR_ROOM_ID_NN NOT NULL
        CONSTRAINT RR_ROOM_ID_FK REFERENCES ROOM(ROOM_ID) ON DELETE RESTRICT,
    CONSTRAINT RR_PK PRIMARY KEY (RESERVATION_ID, ROOM_ID)
);

-- =====================================================
-- PAYMENT
-- =====================================================
CREATE TABLE PAYMENT (
    PAYMENT_ID NUMBER CONSTRAINT PAYMENT_PAYMENT_ID_PK PRIMARY KEY,
    RESERVATION_ID NUMBER CONSTRAINT PAYMENT_RESERVATION_ID_NN NOT NULL
        CONSTRAINT PAYMENT_RESERVATION_ID_FK REFERENCES RESERVATION(RESERVATION_ID) ON DELETE CASCADE,
    AMOUNT NUMBER(10,2) CONSTRAINT PAYMENT_AMOUNT_NN NOT NULL
        CONSTRAINT PAYMENT_AMOUNT_CHK CHECK (AMOUNT >= 0),
    PAYMENT_METHOD VARCHAR2(20) CONSTRAINT PAYMENT_METHOD_NN NOT NULL
        CONSTRAINT PAYMENT_METHOD_CHK CHECK (PAYMENT_METHOD IN ('CASH','CARD','ONLINE','CHEQUE')),
    PAYMENT_DATE DATE CONSTRAINT PAYMENT_DATE_NN NOT NULL
);

-- =====================================================
-- SERVICE_RECORD
-- =====================================================
CREATE TABLE SERVICE_RECORD (
    SERVICE_RECORD_ID NUMBER CONSTRAINT SR_ID_PK PRIMARY KEY,
    RESERVATION_ID NUMBER CONSTRAINT SR_RES_ID_NN NOT NULL
        CONSTRAINT SR_RES_ID_FK REFERENCES RESERVATION(RESERVATION_ID) ON DELETE CASCADE,
    SERVICE_ID NUMBER CONSTRAINT SR_SERVICE_ID_NN NOT NULL
        CONSTRAINT SR_SERVICE_ID_FK REFERENCES SERVICE(SERVICE_ID) ON DELETE RESTRICT,
    STAFF_ID NUMBER CONSTRAINT SR_STAFF_ID_NN NOT NULL
        CONSTRAINT SR_STAFF_ID_FK REFERENCES STAFF(STAFF_ID) ON DELETE RESTRICT,
    ROOM_ID NUMBER CONSTRAINT SR_ROOM_ID_NN NOT NULL
        CONSTRAINT SR_ROOM_ID_FK REFERENCES ROOM(ROOM_ID) ON DELETE RESTRICT,
    QUANTITY NUMBER CONSTRAINT SR_QTY_NN NOT NULL
        CONSTRAINT SR_QTY_CHK CHECK (QUANTITY > 0)
);

  -----------------------------------------------------------------
  -- INSERT SAMPLE DATA
  -----------------------------------------------------------------

  -- GUESTS
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'John Doe', '0912345678', 'john@example.com', 'Manila');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Maria Santos', '0998765432', 'maria@example.com', 'Quezon City');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Alex Cruz', '0922113344', 'alex@example.com', 'Cebu');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Leon Gomez', '0912998877', 'leon@example.com', 'Davao');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Anna Rivera', '09175551234', 'anna@example.com', 'Taguig');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Liam Santos', '09335551212', 'liam@example.com', 'Laguna');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Sophia Lim', '09446671212', 'sophia@example.com', 'Pasig');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'David Tan', '09181112222', 'david@example.com', 'Makati');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Chloe Uy', '09229994433', 'chloe@example.com', 'Cavite');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Gabriel Dela Cruz', '09334455667', 'gabriel@example.com', 'Baguio');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Isabella Torres', '09556677889', 'isabella@example.com', 'Antipolo');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Miguel Herrera', '09668889900', 'miguel@example.com', 'Bulacan');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Ava Delgado', '09223334455', 'ava@example.com', 'Pampanga');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Ethan Reyes', '09771112233', 'ethan@example.com', 'Batangas');
  INSERT INTO GUEST (GUEST_ID, NAME, CONTACT_NO, EMAIL, ADDRESS)
  VALUES (GUEST_SEQ.NEXTVAL, 'Camila Cruz', '09190001122', 'camila@example.com', 'Tarlac');

  -- HOTELS
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Grand Hotel', 'Manila');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Oceanview Resort', 'Cebu');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Mountain Peak Lodge', 'Baguio');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Skyline Suites', 'Makati');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Sunrise Inn', 'Davao');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Holiday Stay', 'Tagaytay');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Palm Grove Hotel', 'Boracay');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Metro Hotel', 'Pasig');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Lakeside Retreat', 'Laguna');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'City Central Hotel', 'Quezon City');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Harborfront Suites', 'Subic');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Forest Cabin Resort', 'Bukidnon');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Paradise Cove', 'Palawan');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Urban Nest Hotel', 'Mandaluyong');
  INSERT INTO HOTEL (HOTEL_ID, NAME, LOCATION) VALUES (HOTEL_SEQ.NEXTVAL, 'Royal Crown Hotel', 'Cavite');



  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Manager');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Receptionist');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Housekeeping');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Chef');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Security');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Waiter');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Bartender');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Maintenance');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Cleaner');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Laundry Staff');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Driver');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Concierge');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Front Desk');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Event Planner');
  INSERT INTO ROLE(ROLE_ID, NAME) VALUES(ROLE_SEQ.NEXTVAL, 'Spa Therapist');


  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 1, 'Ahmed Raza', '03001110001', 'ahmed@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 2, 'Fatima Ali', '03001110002', 'fatima@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 3, 'Kamran Shah', '03001110003', 'kamran@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 4, 'Nida Khan', '03001110004', 'nida@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 5, 'Bilal Qureshi', '03001110005', 'bilal@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 6, 'Sadia Iqbal', '03001110006', 'sadia@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 1, 7, 'Omar Farooq', '03001110007', 'omar@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 8, 'Hira Shah', '03001110008', 'hira@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 9, 'Adeel Malik', '03001110009', 'adeel@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 10, 'Rabia Khan', '03001110010', 'rabia@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 11, 'Zain Abbas', '03001110011', 'zain@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 12, 'Maria Ijaz', '03001110012', 'maria@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 13, 'Usman Tariq', '03001110013', 'usman@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 14, 'Sana Javed', '03001110014', 'sana@hotel.com');

  INSERT INTO STAFF(STAFF_ID, HOTEL_ID, ROLE_ID, NAME, CONTACT_NO, EMAIL) 
  VALUES(STAFF_SEQ.NEXTVAL, 2, 15, 'Ali Raza', '03001110015', 'ali@hotel.com');



  -- ROOM TYPES
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SINGLE', 1500, 'Standard single room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'DOUBLE', 2500, 'Comfort double room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SUITE', 5000, 'Luxury suite room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SINGLE', 1600, 'Standard single with city view.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'DOUBLE', 2600, 'Double room with balcony.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SUITE', 5200, 'Premium suite.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SINGLE', 1550, 'Economy single room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'DOUBLE', 2700, 'Deluxe double room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SUITE', 5500, 'Executive suite.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SINGLE', 1650, 'Garden single.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'DOUBLE', 2800, 'City double.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SUITE', 6000, 'Presidential suite.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SINGLE', 1500, 'Single room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'DOUBLE', 2500, 'Double room.');
  INSERT INTO ROOM_TYPE (ROOM_TYPE_ID, NAME, RATE, DESCRIPTION) VALUES (ROOM_TYPE_SEQ.NEXTVAL, 'SUITE', 5000, 'Suite room.');

  -- ROOMS (room_type_id values will match ROOM_TYPE_SEQ generated ids in insertion order)
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 1, 1, 'AVAILABLE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 2, 2, 'OCCUPIED');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 3, 3, 'RESERVED');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 4, 4, 'AVAILABLE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 5, 5, 'CLEANING');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 6, 6, 'MAINTENANCE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 7, 7, 'AVAILABLE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 8, 8, 'OCCUPIED');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 9, 9, 'AVAILABLE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 10, 10, 'RESERVED');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 11, 11, 'AVAILABLE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 12, 12, 'MAINTENANCE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 13, 13, 'CLEANING');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 14, 14, 'AVAILABLE');
  INSERT INTO ROOM (ROOM_ID, HOTEL_ID, ROOM_TYPE_ID, STATUS) VALUES (ROOM_SEQ.NEXTVAL, 15, 15, 'OCCUPIED');

  -- SERVICES
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Room Cleaning', 300);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Laundry', 150);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Breakfast', 250);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Airport Pickup', 800);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Massage', 1200);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Spa Package', 2000);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Dinner Buffet', 900);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Mini Bar', 500);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Car Rental', 1500);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Extra Bed', 400);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Gym Access', 300);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Late Checkout', 600);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Early Checkin', 500);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Tour Package', 2500);
  INSERT INTO SERVICE (SERVICE_ID, NAME, SERVICE_CHARGE) VALUES (SERVICE_SEQ.NEXTVAL, 'Room Service Meal', 700);

  -- RESERVATIONS (using SYSDATE +/- to simulate dates)
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 1, SYSDATE-20, SYSDATE-15, SYSDATE-13, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 2, SYSDATE-10, SYSDATE-7, SYSDATE-5, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 3, SYSDATE-3, SYSDATE-1, SYSDATE+1, 'CHECKED_IN');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 4, SYSDATE-2, SYSDATE+1, SYSDATE+3, 'BOOKED');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 5, SYSDATE-1, SYSDATE+2, SYSDATE+4, 'BOOKED');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 6, SYSDATE-5, SYSDATE-3, SYSDATE-1, 'CANCELLED');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 7, SYSDATE-9, SYSDATE-6, SYSDATE-4, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 8, SYSDATE-12, SYSDATE-10, SYSDATE-8, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 9, SYSDATE-7, SYSDATE-5, SYSDATE-3, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 10, SYSDATE-1, SYSDATE+1, SYSDATE+2, 'BOOKED');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 11, SYSDATE-4, SYSDATE-2, SYSDATE, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 12, SYSDATE-2, SYSDATE, SYSDATE+2, 'CHECKED_IN');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 13, SYSDATE-3, SYSDATE, SYSDATE+1, 'BOOKED');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 14, SYSDATE-8, SYSDATE-5, SYSDATE-2, 'CHECKED_OUT');
  INSERT INTO RESERVATION (RESERVATION_ID, GUEST_ID, RESERVATION_DATE, CHECKIN_DATE, CHECKOUT_DATE, STATUS)
  VALUES (RESERVATION_SEQ.NEXTVAL, 15, SYSDATE-1, SYSDATE+2, SYSDATE+3, 'BOOKED');


  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (1, 1);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (2, 2);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (3, 3);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (4, 4);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (5, 5);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (6, 6);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (7, 7);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (8, 8);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (9, 9);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (10, 10);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (11, 11);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (12, 12);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (13, 13);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (14, 14);
  INSERT INTO RESERVATION_ROOM (RESERVATION_ID, ROOM_ID) VALUES (15, 15);

  -- PAYMENTS
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 1, 5000, 'CARD', SYSDATE-13);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 2, 3200, 'CASH', SYSDATE-5);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 3, 4500, 'ONLINE', SYSDATE-1);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 4, 2800, 'CARD', SYSDATE-1);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 5, 3000, 'CASH', SYSDATE);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 6, 1000, 'ONLINE', SYSDATE-1);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 7, 3500, 'CARD', SYSDATE-4);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 8, 4200, 'ONLINE', SYSDATE-8);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 9, 3900, 'CARD', SYSDATE-3);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 10, 2500, 'CASH', SYSDATE);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 11, 4100, 'ONLINE', SYSDATE);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 12, 4800, 'CARD', SYSDATE);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 13, 2600, 'ONLINE', SYSDATE);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 14, 3300, 'CASH', SYSDATE-2);
  INSERT INTO PAYMENT (PAYMENT_ID, RESERVATION_ID, AMOUNT, PAYMENT_METHOD, PAYMENT_DATE) VALUES (PAYMENT_SEQ.NEXTVAL, 15, 2900, 'CARD', SYSDATE);

  -- SERVICE_RECORDS
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 1, 1, 1, 1, 1);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 2, 2, 2, 2, 2);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 3, 3, 3, 3, 1);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 4, 4, 4, 4, 2);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 5, 5, 5, 5, 1);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 6, 6, 6, 6, 3);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 7, 7, 7, 7, 2);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 8, 8, 8, 8, 1);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 9, 9, 9, 9, 2);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 10, 10, 10, 10, 3);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 11, 11, 11, 11, 1);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 12, 12, 12, 12, 2);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 13, 13, 13, 13, 1);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 14, 14, 14, 14, 4);
  INSERT INTO SERVICE_RECORD (SERVICE_RECORD_ID, RESERVATION_ID, SERVICE_ID, STAFF_ID, ROOM_ID, QUANTITY) VALUES (SERVICE_RECORD_SEQ.NEXTVAL, 15, 15, 15, 15, 3);



  COMMIT;

